{exec} = require 'child_process'

task 'build', 'Build project from Coffee/ to JS/', ->
  exec 'coffee -o JS/ -c Coffee/*.coffee', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr
  exec 'uglifyjs JS/TextShower.js -o JS/TextShower.min.js'

task 'watch', 'Watch changes', ->
  exec 'coffee -o JS/ -cw Coffee/*.coffee', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr